import { CLUE_SET_SCHEMA, type ClueSet } from './clue-set';

export const CLUE_SET_PRESETS: readonly ClueSet[] = [
  {
    schema: CLUE_SET_SCHEMA,
    id: 'animaux-fr-v1',
    name: 'Animaux — définitions & détours',
    language: 'fr',
    description: 'Couverture complète du WordSet Animaux avec quelques variantes éditoriales.',
    license: 'CC0-1.0',
    author: 'Cruciverbalis',
    clues: [
      { id: 'chat-definition', answer: 'CHAT', kind: 'definition', text: 'Petit félin domestique amateur de siestes et de hauteurs.', difficulty: 1 },
      { id: 'chat-wordplay', answer: 'CHAT', kind: 'wordplay', text: 'Il ronronne parfois mieux qu’un moteur bien réglé.', difficulty: 2 },
      { id: 'chien-definition', answer: 'CHIEN', kind: 'definition', text: 'Mammifère domestique souvent décrit comme le meilleur ami de l’être humain.', difficulty: 1 },
      { id: 'renard-definition', answer: 'RENARD', kind: 'definition', text: 'Canidé roux réputé pour sa ruse dans les fables.', difficulty: 1 },
      { id: 'lion-definition', answer: 'LION', kind: 'definition', text: 'Grand félin africain dont le mâle porte généralement une crinière.', difficulty: 1 },
      { id: 'tigre-definition', answer: 'TIGRE', kind: 'definition', text: 'Grand félin asiatique reconnaissable à ses rayures.', difficulty: 1 },
      { id: 'loutre-definition', answer: 'LOUTRE', kind: 'definition', text: 'Mammifère semi-aquatique agile, souvent observé flottant sur le dos.', difficulty: 2 },
      { id: 'panda-definition', answer: 'PANDA', kind: 'definition', text: 'Grand mammifère noir et blanc dont le bambou constitue l’essentiel du régime.', difficulty: 1 },
      { id: 'aigle-definition', answer: 'AIGLE', kind: 'definition', text: 'Grand rapace diurne à la vue particulièrement perçante.', difficulty: 1 },
    ],
    provenance: { createdBy: 'cruciverbalis', source: 'built-in-preset' },
  },
  {
    schema: CLUE_SET_SCHEMA,
    id: 'energie-fr-v1',
    name: 'Énergie et choix techniques',
    language: 'fr',
    description: 'Couverture complète du WordSet Énergie avec définitions et formulations plus éditoriales.',
    license: 'CC0-1.0',
    author: 'Cruciverbalis',
    clues: [
      { id: 'nucleaire-definition', answer: 'NUCLEAIRE', kind: 'definition', text: 'Qui concerne l’énergie issue de transformations du noyau atomique.', difficulty: 2 },
      { id: 'nucleaire-wordplay', answer: 'NUCLEAIRE', kind: 'wordplay', text: 'Une énergie où tout se joue au cœur de l’atome.', difficulty: 3 },
      { id: 'sobriete-definition', answer: 'SOBRIETE', kind: 'definition', text: 'Réduction volontaire des consommations ou des usages.', difficulty: 2 },
      { id: 'energie-definition', answer: 'ENERGIE', kind: 'definition', text: 'Grandeur physique associée à la capacité d’un système à produire un travail ou une transformation.', difficulty: 1 },
      { id: 'uranium-definition', answer: 'URANIUM', kind: 'definition', text: 'Élément chimique lourd utilisé comme combustible dans certains réacteurs.', difficulty: 2 },
      { id: 'dechet-definition', answer: 'DECHET', kind: 'definition', text: 'Résidu issu d’une activité et dont il faut assurer le traitement ou la gestion.', difficulty: 1 },
      { id: 'carbone-definition', answer: 'CARBONE', kind: 'definition', text: 'Élément chimique au cœur de nombreuses molécules organiques et des émissions de CO₂.', difficulty: 2 },
      { id: 'risque-definition', answer: 'RISQUE', kind: 'definition', text: 'Possibilité qu’un événement dommageable survienne.', difficulty: 1 },
      { id: 'temps-analogy', answer: 'TEMPS', kind: 'analogy', text: 'Aux choix techniques ce que la profondeur est à un paysage : une dimension qu’on oublie facilement.', difficulty: 3 },
    ],
    provenance: { createdBy: 'cruciverbalis', source: 'built-in-preset' },
  },
  {
    schema: CLUE_SET_SCHEMA,
    id: 'linux-fr-v1',
    name: 'Linux — technique & culture',
    language: 'fr',
    description: 'Couverture complète du WordSet Linux avec indices techniques, historiques et joueurs.',
    license: 'CC0-1.0',
    author: 'Cruciverbalis',
    clues: [
      { id: 'linux-definition', answer: 'LINUX', kind: 'definition', text: 'Famille de systèmes d’exploitation construits autour d’un noyau libre.', difficulty: 1 },
      { id: 'noyau-analogy', answer: 'NOYAU', kind: 'analogy', text: 'Au système d’exploitation ce que le cœur est à un organisme.', difficulty: 2 },
      { id: 'terminal-definition', answer: 'TERMINAL', kind: 'definition', text: 'Interface textuelle permettant d’interagir avec le système via des commandes.', difficulty: 1 },
      { id: 'fedora-historical', answer: 'FEDORA', kind: 'historical', text: 'Distribution communautaire liée à Red Hat et lancée au début des années 2000.', difficulty: 3 },
      { id: 'shell-wordplay', answer: 'SHELL', kind: 'wordplay', text: 'Coquille où l’on tape parfois bien plus qu’on ne mange.', difficulty: 3 },
      { id: 'paquet-definition', answer: 'PAQUET', kind: 'definition', text: 'Unité distribuable regroupant un logiciel et les métadonnées nécessaires à son installation.', difficulty: 2 },
      { id: 'daemon-etymology', answer: 'DAEMON', kind: 'etymology', text: 'Nom informatique hérité d’un esprit intermédiaire de la mythologie grecque.', difficulty: 4 },
      { id: 'source-definition', answer: 'SOURCE', kind: 'definition', text: 'Texte d’un programme avant compilation ou interprétation.', difficulty: 1 },
    ],
    provenance: { createdBy: 'cruciverbalis', source: 'built-in-preset' },
  },
  {
    schema: CLUE_SET_SCHEMA,
    id: 'espace-fr-v1',
    name: 'Espace — astronomie & exploration',
    language: 'fr',
    description: 'Couverture complète du WordSet Espace avec indices accessibles et quelques détours.',
    license: 'CC0-1.0',
    author: 'Cruciverbalis',
    clues: [
      { id: 'etoile-definition', answer: 'ETOILE', kind: 'definition', text: 'Astre produisant sa propre lumière grâce aux réactions qui ont lieu en son cœur.', difficulty: 1 },
      { id: 'planete-definition', answer: 'PLANETE', kind: 'definition', text: 'Corps céleste en orbite autour d’une étoile et suffisamment massif pour être presque sphérique.', difficulty: 1 },
      { id: 'galaxie-definition', answer: 'GALAXIE', kind: 'definition', text: 'Immense ensemble d’étoiles, de gaz et de matière liés par la gravitation.', difficulty: 2 },
      { id: 'comete-definition', answer: 'COMETE', kind: 'definition', text: 'Petit corps glacé pouvant développer une queue lumineuse près du Soleil.', difficulty: 2 },
      { id: 'orbitale-definition', answer: 'ORBITALE', kind: 'definition', text: 'Région de l’espace décrivant la distribution probable d’un électron autour d’un noyau.', difficulty: 3 },
      { id: 'satellite-definition', answer: 'SATELLITE', kind: 'definition', text: 'Objet naturel ou artificiel placé en orbite autour d’un astre.', difficulty: 1 },
      { id: 'nebuleuse-definition', answer: 'NEBULEUSE', kind: 'definition', text: 'Nuage interstellaire de gaz et de poussières, parfois berceau d’étoiles.', difficulty: 2 },
      { id: 'cosmos-analogy', answer: 'COSMOS', kind: 'analogy', text: 'À l’univers ce que la forêt est aux arbres : le tout plutôt qu’un seul de ses objets.', difficulty: 2 },
    ],
    provenance: { createdBy: 'cruciverbalis', source: 'built-in-preset' },
  },
  {
    schema: CLUE_SET_SCHEMA,
    id: 'fruit-fr-v1',
    name: 'Fruits — styles variés',
    language: 'fr',
    description: 'Petit corpus éditorial de démonstration, non associé à un WordSet prédéfini.',
    license: 'CC0-1.0',
    author: 'Cruciverbalis',
    clues: [
      { id: 'pasteque-definition', answer: 'PASTEQUE', kind: 'definition', text: 'Gros fruit à chair rouge et très riche en eau.', difficulty: 1 },
      { id: 'pasteque-wordplay', answer: 'PASTEQUE', kind: 'wordplay', text: 'Elle a le cœur rouge mais ne bat jamais.', difficulty: 3 },
      { id: 'citron-definition', answer: 'CITRON', kind: 'definition', text: 'Agrume jaune à la saveur très acide.', difficulty: 1 },
      { id: 'citron-wordplay', answer: 'CITRON', kind: 'wordplay', text: 'Il fait parfois grimacer avant même qu’on le presse.', difficulty: 3 },
      { id: 'pomme-historical', answer: 'POMME', kind: 'historical', text: 'Fruit devenu symbole scientifique dans la légende associée à Newton.', difficulty: 2 },
      { id: 'orange-analogy', answer: 'ORANGE', kind: 'analogy', text: 'Au fruit ce que son nom est aussi à une couleur.', difficulty: 2 },
    ],
    provenance: { createdBy: 'cruciverbalis', source: 'built-in-preset' },
  },
];

export function findClueSetPreset(id: string): ClueSet | undefined {
  return CLUE_SET_PRESETS.find((preset) => preset.id === id);
}
